#!/bin/bash
# Apply Migration 005: Atomic Document Deletion Function
# 
# This script provides instructions for applying the migration.
# Supabase requires migrations to be run via the Dashboard or CLI.

echo "============================================"
echo "Migration 005: Atomic Document Deletion"
echo "============================================"
echo ""
echo "⚠️  IMPORTANT: This migration must be applied manually"
echo ""
echo "📋 Steps:"
echo ""
echo "1. Open Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/YOUR_PROJECT_ID/sql/new"
echo ""
echo "2. Copy the migration file:"
echo "   cat backend/migrations/005_add_delete_document_function.sql | pbcopy"
echo "   (Or manually copy: backend/migrations/005_add_delete_document_function.sql)"
echo ""
echo "3. Paste into SQL Editor and click 'Run'"
echo ""
echo "4. Verify success:"
echo "   You should see: 'Created delete_document_with_chunks() function with RLS enforcement'"
echo ""
echo "5. Test the function:"
echo "   SELECT * FROM delete_document_with_chunks('00000000-0000-0000-0000-000000000000');"
echo "   Expected: {\"deleted\": false, \"error\": \"Document not found or access denied\"}"
echo ""
echo "============================================"
echo ""
echo "After applying, run tests:"
echo "  cd backend"
echo "  uv run pytest tests/test_atomic_deletion.py -v"
echo ""
