"""
Database models for Advanced Agentic RAG.

These Pydantic models represent the structure of our Supabase database tables.
They provide type safety, validation, and documentation for database operations.

Design Philosophy:
- Pydantic (not SQLAlchemy ORM) because Supabase uses its own client
- Models mirror the exact schema defined in docs/04_DB_Design.md
- Optional fields use `None` default to match database nullable columns
- JSONB fields use `dict` type for flexible metadata storage

Learning Note:
These models are used for:
1. Type hints in repository functions (type safety)
2. Validation when creating/updating records
3. Serialization when reading from database
4. Documentation of the database schema
"""

from datetime import UTC, datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator


# Helper function for UTC timestamps
def utc_now() -> datetime:
    """Return current UTC time (timezone-aware)."""
    return datetime.now(UTC)


# ============================================================================
# ENUMS - Define allowed values for status fields
# ============================================================================


class DocumentStatus(str, Enum):
    """
    Document processing status.

    Workflow:
    - PENDING: Document uploaded, not yet processed
    - PROCESSING: Currently being parsed, chunked, and embedded
    - COMPLETED: Successfully processed and stored in vector store
    - FAILED: Processing failed (error details stored in metadata)

    Learning Note:
    Using Enum ensures only valid statuses can be set, preventing typos.
    """

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class ChunkType(str, Enum):
    """
    Type of chunk in parent-child indexing strategy.

    Parent-Child Chunking:
    - PARENT: Large context chunk (not embedded, provides context)
    - CHILD: Small searchable chunk (embedded, used for retrieval)

    Learning Note:
    This enables "small-to-big" retrieval: search small chunks,
    return parent chunks for more context.
    """

    PARENT = "parent"
    CHILD = "child"


# ============================================================================
# BASE MODELS - Shared fields for all database models
# ============================================================================


class TimestampMixin(BaseModel):
    """
    Mixin for created_at and updated_at timestamps.

    Learning Note:
    Mixins are reusable pieces of model definitions.
    All database records should track when they were created/modified.
    """

    created_at: datetime = Field(
        default_factory=utc_now, description="When this record was created (UTC)"
    )
    updated_at: datetime = Field(
        default_factory=utc_now, description="When this record was last updated (UTC)"
    )


# ============================================================================
# SOURCE MODEL - Logical container for documents
# ============================================================================


class Source(TimestampMixin):
    """
    Represents a logical grouping of documents (like a folder).

    Example Use Cases:
    - "Prisma Docs" source contains all Prisma documentation
    - "Stripe API" source contains all Stripe API references

    RLS (Row-Level Security):
    - user_id ensures users can only see their own sources

    Fields:
    - id: UUID primary key (auto-generated by Supabase)
    - user_id: Clerk user ID (e.g., "user_2b...")
    - name: Display name shown in UI
    - description: Optional context for the AI agent
    """

    id: UUID = Field(description="Unique identifier for this source")
    user_id: str = Field(description="Clerk user ID who owns this source")
    name: str = Field(
        min_length=1,
        max_length=255,
        description="Human-readable name (e.g., 'Prisma Documentation')",
    )
    description: str | None = Field(
        default=None, description="Optional context for the AI (e.g., 'Use for database queries')"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "user_id": "user_2bXYZ123",
                "name": "LangGraph Documentation",
                "description": "Official LangGraph docs for building agentic workflows",
                "created_at": "2026-01-19T10:00:00Z",
                "updated_at": "2026-01-19T10:00:00Z",
            }
        }
    )


# ============================================================================
# DOCUMENT MODEL - Represents a file uploaded by a user
# ============================================================================


class Document(TimestampMixin):
    """
    Represents a raw file (Markdown, PDF) uploaded and processed by the system.

    Processing Workflow:
    1. User uploads file → status = PENDING
    2. Backend parses file → status = PROCESSING
    3. Backend chunks + embeds → status = COMPLETED (or FAILED)

    Storage:
    - File content processed in-memory during ingestion
    - Optional blob_path for permanent storage in Supabase Storage
    - Metadata and status tracked in this database table

    Deduplication:
    - content_hash field (SHA256) prevents uploading the same file twice
    - Hash computed from raw file bytes before processing

    Fields:
    - id: UUID primary key
    - user_id: Owner (from JWT token, enforced by RLS)
    - title: Filename or document title
    - file_type: Format (markdown, pdf, txt)
    - file_size: Size in bytes
    - content_hash: SHA256 hash for deduplication
    - chunk_count: Number of chunks created from this document
    - status: Current processing state
    - source_id: Optional parent source/collection ID
    - blob_path: Optional path in Supabase Storage
    - metadata: Flexible JSONB metadata (tags, categories, etc.)
    """

    id: UUID = Field(default_factory=uuid4, description="Unique identifier for this document")
    user_id: str = Field(description="Owner user ID (Clerk user ID, enforced by RLS)")
    title: str = Field(min_length=1, max_length=500, description="Document title or filename")
    file_type: str = Field(description="File format (markdown, pdf, txt, etc.)")
    file_size: int = Field(ge=0, description="File size in bytes")
    content_hash: str = Field(description="SHA256 hash of content for deduplication")
    chunk_count: int = Field(
        default=0, ge=0, description="Number of chunks created from this document"
    )
    status: DocumentStatus = Field(
        default=DocumentStatus.PENDING, description="Current processing status"
    )
    source_id: UUID | None = Field(
        default=None, description="Optional parent source/collection this document belongs to"
    )
    blob_path: str | None = Field(
        default=None,
        description="Optional path in Supabase Storage (e.g., 'user_123/docs/guide.md')",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Flexible JSONB metadata (tags, categories, parser info, etc.)",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "660e8400-e29b-41d4-a716-446655440001",
                "user_id": "user_2bXYZ123",  # Clerk user ID format
                "title": "LangGraph Quick Start",
                "file_type": "markdown",
                "file_size": 8530,
                "content_hash": "a3b5c7d9e1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4",
                "chunk_count": 12,
                "status": "completed",
                "source_id": "550e8400-e29b-41d4-a716-446655440000",
                "blob_path": None,
                "metadata": {
                    "source": "langgraph-docs",
                    "category": "quickstart",
                    "original_filename": "quickstart.md",
                },
                "created_at": "2026-01-19T10:05:00Z",
                "updated_at": "2026-01-19T10:07:00Z",
            }
        }
    )


# ============================================================================
# DOCUMENT CHUNK MODEL - The core of the RAG system
# ============================================================================


class DocumentChunk(TimestampMixin):
    """
    Represents a piece of text extracted from a document.

    THIS IS THE MOST CRITICAL MODEL FOR RAG:
    - Stores the actual text content
    - Stores the vector embedding (for semantic search)
    - Stores metadata (page numbers, headers, code language, etc.)

    Chunking Strategy:
    - Large documents are split into smaller pieces (chunks)
    - Each chunk is embedded independently
    - Chunks have overlap to preserve context across boundaries

    Metadata Structure (JSONB):
    {
        "header": "Authentication",           # Section header
        "page": 5,                            # Page number (if PDF)
        "language": "typescript",             # Programming language (if code)
        "chunk_strategy": "recursive",        # Which chunker created this
        "parent_header_chain": ["Docs", "API", "Auth"],  # Breadcrumb trail
        "semantic_density": 0.85,             # Information density score
        "context_prefix": "[Doc: LangGraph | Section: Agents]"  # Contextual enrichment
    }

    Parent-Child Indexing:
    - parent_chunk_id: If this is a child chunk, references the parent
    - chunk_type: PARENT (context) or CHILD (searchable)

    Fields:
    - id: UUID primary key
    - document_id: Which document this came from
    - user_id: Owner (denormalized for RLS)
    - chunk_index: Order in document (0, 1, 2, ...)
    - content: The actual text
    - metadata: Flexible JSONB for contextual information
    - embedding: Vector for semantic search (nullable until generated)
    - parent_chunk_id: For parent-child chunking
    - chunk_type: PARENT or CHILD
    """

    id: UUID = Field(description="Unique identifier for this chunk")
    document_id: UUID = Field(description="Parent document this chunk was extracted from")
    user_id: str = Field(description="Owner (denormalized for RLS performance)")
    chunk_index: int = Field(ge=0, description="Sequential order in document (0-based)")
    content: str = Field(min_length=1, description="The actual text content of this chunk")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Flexible JSONB storage for chunk context (headers, page nums, etc.)",
    )
    embedding: list[float] | None = Field(
        default=None,
        description="Vector embedding (generated async by OpenAI text-embedding-3-small)",
    )
    parent_chunk_id: UUID | None = Field(
        default=None, description="If this is a child chunk, references the parent chunk"
    )
    chunk_type: ChunkType = Field(
        default=ChunkType.PARENT, description="PARENT (context) or CHILD (searchable)"
    )

    @field_validator("embedding")
    @classmethod
    def validate_embedding_dimensions(cls, v: list[float] | None) -> list[float] | None:
        """
        Validate embedding vector dimensions.

        Learning Note:
        OpenAI text-embedding-3-small produces 1536-dimensional vectors.
        This validator ensures the embedding has the correct size.

        Why 1536 instead of 3072?
        - HNSW index limit: pgvector HNSW supports max 2000 dimensions
        - Cost efficiency: 1536 is 6.5x cheaper ($0.02 vs $0.13 per 1M tokens)
        - Performance: 95% accuracy of 3072, but 2x faster
        - Industry standard: Most production RAG systems use 1536
        """
        if v is not None and len(v) != 1536:
            raise ValueError(f"Embedding must be 1536 dimensions, got {len(v)}")
        return v

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "770e8400-e29b-41d4-a716-446655440002",
                "document_id": "660e8400-e29b-41d4-a716-446655440001",
                "user_id": "user_2bXYZ123",
                "chunk_index": 0,
                "content": "LangGraph is a framework for building stateful, multi-agent applications...",
                "metadata": {
                    "header": "Introduction",
                    "chunk_strategy": "recursive",
                    "semantic_density": 0.82,
                    "context_prefix": "[Doc: LangGraph Quick Start | Section: Introduction]",
                },
                "embedding": [0.123, -0.456, 0.789, "... (1536 dimensions)"],
                "parent_chunk_id": None,
                "chunk_type": "parent",
                "created_at": "2026-01-19T10:07:00Z",
                "updated_at": "2026-01-19T10:07:00Z",
            }
        }
    )


# ============================================================================
# FEEDBACK MODEL - User feedback tracking
# ============================================================================


class FeedbackType(str, Enum):
    """
    Type of feedback submitted by the user.

    Options:
    - BUG: Something is broken
    - FEATURE_REQUEST: New functionality desired
    - GENERAL: General comments
    - OTHER: Everything else
    """

    BUG = "bug"
    FEATURE_REQUEST = "feature_request"
    GENERAL = "general"
    OTHER = "other"


class Feedback(TimestampMixin):
    """
    Represents user feedback submitted through the application.

    Fields:
    - id: UUID primary key
    - user_id: User who submitted the feedback
    - feedback_type: Category of feedback
    - message: The actual feedback content
    - rating: 1-5 star rating
    """

    id: UUID = Field(default_factory=uuid4, description="Unique identifier for this feedback")
    user_id: str = Field(description="Clerk user ID who submitted the feedback")
    feedback_type: FeedbackType = Field(description="Type of feedback (bug, feature, etc.)")
    message: str = Field(min_length=10, description="Feedback content")
    rating: int = Field(ge=1, le=5, description="Rating from 1 to 5")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "770e8400-e29b-41d4-a716-446655440003",
                "user_id": "user_2bXYZ123",
                "feedback_type": "feature_request",
                "message": "It would be great to have dark mode support.",
                "rating": 5,
                "created_at": "2026-02-17T12:00:00Z",
                "updated_at": "2026-02-17T12:00:00Z",
            }
        }
    )
